version: '1'
services:
  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     - GOOGLE_CLIENT_ID: "510632257466-7ebmto0f084dm9ho9oc3u5ealuprivlb.apps.googleusercontent.com"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '2.0'
        reservations:
          cpus: '1.0'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    environment:
      # XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          cpus: '2.0'
        reservations:
          cpus: '1.0'

  # # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
